	<footer>
		<ul class="left">
			<li>Hosted and powered by <a href="http://get.harmonyapp.com">Harmony</a></li>

			<li class="no_border reset"><a href="http://twitter.com/bylinebreak">Twitter</a></li>
		</ul>

		<ul class="right">
			<li>{% copyright 2010 %} Linebreak, S.L. All rights reserved worldwide.</li>
		</ul>
	</footer>
</div>

<script src="http://static.getclicky.com/js" type="text/javascript"></script>
<script type="text/javascript">clicky.init(175522);</script>
<noscript><img alt="Clicky" width="1" height="1" src="http://static.getclicky.com/175522ns.gif" /></noscript>
</body>
</html>